### ISSUE TITLE
Once finalized, certain parts of this codebase should be extracted.

### ISSUE THREAD

**Issue by kayabaNerve** [kayabaNerve/nim-protobuf-serialization#19]
The internal file has a set of flatMap/box macros. Most nim-serializations libraries use a recursive technique, yet these macros offer a cleaner solution (in my opinion) with less call depth. They may be valuable as part of the core library.

In regards to https://github.com/kayabaNerve/nim-protobuf-serialization/issues/9, there's currently two VarInt implementations floating around Status. One is in Stew, and limited. It implements Protobuf's uint and zig-zag encoding. One is in libp2p, and implements all protobuf variants, as well as the libp2p variants. As the one in Stew is literally an old version's of libp2p, it's effectively ignorable. For now, I plan to copy libp2p's implementation to this project, where it can be easily modified and tested, and map the existing Protobuf API to it (as attempted, unsuccessfully, in the current VarInt test). I'm honestly quite preferential to the API in this library as it properly handles type safety and is bit-agnostic. That said, it doesn't handle all the error cases libp2p's does, so it needs modification.

Once mapped properly, without changing the underlying implementation, it can be verified. Once verified, they can be integrated. Once integrated, it should be moved. It could either replace Stew's implementation, replace libp2p's, be merged into faststreams, or become an independent library.

That said, while the Status implementations use "flavours"/types, this library solely uses types. Where as Status uses enum returned code, this library uses a generic Exception. I'd like the integrated version to use solely types, but potentially offer a flavor overload to support older APIs. I also think it should still return enums, and the Protobuf library should raise on any non-success enum value.

None of this should be acted on right now. I just want to create an issue in order to think about the future of this library.

**Comment by kayabaNerve** [comment]
Oh. I also want to note I'm not happy with the box macro, despite being happy with the flatType/flatMap macros. It's just not clean code.

**Comment by zah** [comment]
The main idea of the Stew library is that it offers a stateful Varint parser that can be fed byte by byte. This makes the streaming use cases easier to handle (in particular, it allows an efficient integration with FastStreams).

The current code in Stew was translated 1:1 from the LibP2P implementation and I don't see why it can't be done again.

Since a Varint library usually deals with untrusted input (error should be cheap to handle) and it's simple enough (there are only few things that could go wrong), I think an enum error code is the best way to report an error there (just like it's done currently in Stew). The use of exceptions will lead to a significant decrease of the execution speed in the Error case without adding much value in terms of reducing the complexity of the code or adding richer error infromation. With that said, it would be perfectly fine for ProtoBuf to translate this lower-level error code into an exception that will propagate through the nim-serialization APIs.

**Comment by zah** [comment]
With regard to `flavours` vs `types`, there is not much practical difference between these two choices really. 

When you create a generic API that accept a type, you are saying "My library is open for extensibility by allowing you to instantiate it with new types". You have to think through all the implications of this. You'll have to document what the new type must implement in order to be compatible with the library.

When you use a static enum value, you are saying "My library support a fixed set of options that should be enough for your needs". Nim helps along the way by requiring you to cover all supported cases in case statements and the like. When you work with externally defined standards, the enum value is probably a better fit, because the supported enum values should just represent the options provided by the standard.

**Comment by kayabaNerve** [comment]
Thanks for the notes.

While I agree enum return codes, the point of types was two-fold.

1) Argument consolidatation.
2) Compile-time checks for type safety.

This library originally kept track of a VarInt encoding enum, yet it quickly become problematic when dealing with both objects and primitives. While nim-serialization offers `.encode(value, FLAGS)`, an API I had not exposed at that time, this leads into the second point.

I always preferred the compile-time safety of a type system than a runtime check. While you can easily mute those compile-time checks and do runtime switches, I truly appreciate having a compile-time error when attaching an invalid encoding to a unsupported number. The encoding types I wrote are never directly accessed; they're always attached via a template.

That said, I do completely understand the point about how it looks being a point to consider, as code is only as good as its API. I may look into using a static enum value.

Due to the problems underlying the macros, I'd like to merge this with #9 as that seems to be the only piece of code left up in debate.

**Comment by zah** [comment]
Perhaps I'm misunderstanding your reply, but I'll point out that the `flavour` value is a static generic parameter. It's supposed to be used only in `when` statements, so there are no run-time checks. 

It's really just a matter of having "open" vs "closed" system. As mentioned above, the "closed"  system can actually feature a stricter compile-time verification, because the compiler helps with certain things such as ensuring that all enum cases are covered.

**Comment by kayabaNerve** [comment]
Thanks for the heads up. That's effectively what I was discussing.
